modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/MC-U-Team/Useful-Backpacks/issues"
displayURL="https://u-team.info/mods/usefulbackpacks"
logoFile="logo.png"
license="Apache-2.0 License"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="usefulbackpacks"
	version="${file.jarVersion}"
	displayName="Useful Backpacks"
	updateJSONURL="https://api.u-team.info/update/usefulbackpacks.json"
	description="This mod adds cool new backpacks to your game."
	
	[[dependencies.usefulbackpacks]]
	    modId="forge"
	    mandatory=true
	    versionRange="[33.0.61,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.usefulbackpacks]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.16.2]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.usefulbackpacks]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[3.1.9.180,)"
	    ordering="NONE"
	    side="BOTH"