modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/MC-U-Team/Useful-Backpacks/issues"
displayURL="https://u-team.info/mods/usefulbackpacks"
logoFile="logo.png"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="usefulbackpacks"
	version="${file.jarVersion}"
	displayName="Useful Backpacks"
	updateJSONURL="https://api.u-team.info/update/usefulbackpacks.json"
	description="This mod adds cool new backpacks to your game."
	
	[[dependencies.uteamcore]]
	    modId="forge"
	    mandatory=true
	    versionRange="[25,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.uteamcore]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.13.2]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.uteamcore]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[2.3.0.99-SNAPSHOT,)"
	    ordering="NONE"
	    side="BOTH"