modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MC-U-Team/Useful-Backpacks/issues"
displayURL="https://u-team.info/mods/usefulbackpacks"
logoFile="logo.png"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="usefulbackpacks"
	version="${file.jarVersion}"
	displayName="Useful Backpacks"
	updateJSONURL="https://api.u-team.info/update/usefulbackpacks.json"
	description="This mod adds cool new backpacks to your game."
	
	[[dependencies.usefulbackpacks]]
	    modId="forge"
	    mandatory=true
	    versionRange="[28.1.72,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.usefulbackpacks]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.4]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.usefulbackpacks]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[2.7.6.136,)"
	    ordering="NONE"
	    side="BOTH"